# Generated by Django 5.2.8 on 2025-11-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_downloadhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownloadHistory',
        ),
    ]
